homebrew_packages:
- autoconf
- autojump
- automake
- awscli
- cloc
- coreutils
- enchant
- exiftool
- fd
- fdupes
- ffmpeg
- freetype
- fswatch
- fzf
- gdal
- gdbm
- gh
- git
- git-delta
- goaccess
- gpg
- graphicsmagick
- heroku/brew/heroku
- hyperfine
- inetutils
- jhead
- jpeg
- jpegoptim
- jq
- lesspipe
- libevent
- libmemcached
- libpng
- libtool
- libyaml
- memcached
- mise
- myrepos
- ncdu
- nginx
- openssl
- ossp-uuid
- pandoc
- parallel
- percona-toolkit
- pkg-config
- postgresql@16
- pre-commit
- pwgen
- python
- qpdf
- readline
- rg
- rsync
- rtmpdump
- sd
- shellcheck
- sqlite
- starship
- swig
- tmux
- tree
- watch
- watchman
- wget
- xz
- zlib
- zsh-completions
- zsh-autosuggestions
- zsh-history-substring-search
- zsh-syntax-highlighting

homebrew_cask_packages:
- anki
- calibre
- discord
- docker
- evernote
- firefox
- homebrew/cask-fonts/font-ubuntu-mono-nerd-font
- iterm2
- istat-menus
- java
- karabiner-elements
- keyboard-maestro
- mactex
- rectangle
- skype
- steam
- sublime-text
- tableplus
- vlc

mise_python_versions:
# In precedence order
- '3.12'
- '3.11'
- '3.10'
- '3.9'
- '3.8'
- '3.13.0a5'

pip_packages:
- black
- build
- csvkit
- flake8
- httpie
- ipdb
- ipython
- pip-tools
- pre-commit
- pygments
- pythonpy
- python-language-server
- pyyaml
- requests
- s3cmd
- tox
- tox-uv
- twine
- yt-dlp
- uv
- virtualenv
