- name: Update homebrew
  homebrew:
    name: git
    state: latest
    update_homebrew: true
  tags:
  - brew

- name: Install homebrew packages
  homebrew:
    name: '{{ homebrew_packages }}'
    state: latest
  tags:
  - brew

- name: Install homebrew cask packages
  command: brew install {{ homebrew_cask_packages|join(" ") }}
  tags:
  - brew

- name: Mise install Node
  command: mise latest node@20
  tags:
  - mise

- name: Mise install Ruby
  command: mise latest ruby@3.3
  tags:
  - mise

- name: Mise install Bun
  command: mise latest bun@1.1
  tags:
  - mise

- name: Mise activates
  command: >
    mise use -g
    node@20
    ruby@3.3
    bun@1.1
  tags:
  - mise

- name: Mise reshim
  command: mise reshim
  tags:
  - mise

- name: uv install latest Pythons
  command: uv python install {{ uv_python_versions|join(" ") }}
  tags:
  - uv

- name: uv install tools
  command: >
    uv tool install
    {{ item.name }}
    {% if item.with is defined %}
    {% for w in item.with %}--with {{ w }}{% endfor %}
    {% endif %}
  loop: '{{ uv_tools }}'
  tags:
  - uv

- name: uv upgrade tools
  command: >
    uv tool upgrade
    {{ item.name }}
    {% if item.with is defined %}
    {% for w in item.with %}--upgrade-package {{ w }}{% endfor %}
    {% endif %}
  loop: '{{ uv_tools }}'
  tags:
  - uv

- name: virtualenv update embed wheels
  command: uv tool run virtualenv --upgrade-embed-wheels
  tags:
  - uv
