- name: Update homebrew
  homebrew:
    name: git
    state: latest
    update_homebrew: true
  tags:
  - brew

- name: Install homebrew packages
  homebrew:
    name: '{{ homebrew_packages }}'
    state: latest
  tags:
  - brew

- name: Install homebrew cask packages
  command: brew install {{ homebrew_cask_packages|join(" ") }}
  tags:
  - brew

- name: Mise install Pythons
  command: mise latest python@{{ item }}
  loop: '{{ mise_python_versions }}'
  tags:
  - mise

- name: Mise install Node
  command: mise latest node@20
  tags:
  - mise

- name: Mise install Ruby
  command: mise latest ruby@3.3
  tags:
  - mise

- name: Mise activates
  command: >
    mise use -g
    {% for v in mise_python_versions %}python@{{ v }} {% endfor %}
    node@20
    ruby@3.3
  tags:
  - mise

- name: Install pip packages for all Pythons
  command: >
    mise exec python@{{ item }} --
    python -m pip
    install -U
    pip
    pip-tools
  environment:
    PIP_REQUIRE_VIRTUALENV: "0"
  loop: '{{ mise_python_versions }}'
  tags:
  - mise

- name: Install pip packages for main Python
  command: >
    mise exec python@{{ mise_python_versions[0] }} --
    python -m pip
    install -U
    {{ pip_packages|join(" ") }}
  environment:
    PIP_REQUIRE_VIRTUALENV: "0"
  tags:
  - mise

- name: virtualenv update embed wheels
  command: >
    mise exec python@{{ mise_python_versions[0] }} --
    python -m virtualenv --upgrade-embed-wheels
  environment:
    PIP_REQUIRE_VIRTUALENV: "0"
  tags:
  - mise

- name: Mise reshim
  command: mise reshim
  tags:
  - mise
